FROM mcr.microsoft.com/dotnet/core/runtime:3.1

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

ENV TZ=Europe/Brussels
ENV KEY_VAULT=...
ENV CLIENT_ID=...
ENV CLIENT_SECRET=...
ENV ARENA_SIZE=10

# Start the app
ENTRYPOINT ["dotnet", "CSharpWars.Processor.dll"]