FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Set the working directory
WORKDIR /app

# Copy the app
COPY bin/Release/publish /app

EXPOSE 5000

ENV TZ=Europe/Brussels
ENV KEY_VAULT=...
ENV CLIENT_ID=...
ENV CLIENT_SECRET=...
ENV CERTIFICATE_KEY=...

# Start the app
ENTRYPOINT ["dotnet", "CSharpWars.Web.dll"]